### ISSUE TITLE
Responsive and synchronisation

### ISSUE THREAD

**Issue by rbeer** [stream-sync/iwdsync#1]
Hi! :smiley: 

Very cool project, you started here. Do you take PRs?

I've made the design responsive: https://iwdsync0.herokuapp.com/caster/iwd
It works pretty well on desktop and horizontal mobile; vertical still needs a stacking layout.
The changes are in my [responsive](https://github.com/rbeer/iwdsync/tree/responsive) tree.

I'm currently getting the Twitch video to be resizable and I also thought about the synchronisation problem. It's non-trivial, but we would get to play with QRCodes; and that's always fun. :nerd_face: 

Let me know what you think!

**Comment by brianjp93** [comment]
I'm definitely looking to take PR's!  It's why I opened the code to the public.  I'll take a look at what you have and possibly merge it in.

**Comment by rbeer** [comment]
I'll clean up and open a PR then.
Does IWD have a Discord? In any case, we can jump into a vc for the review if you want/have questions.
